version: '3.9'

services:
  grpc-service-a:
    container_name: grpc-service-a
    build:
        context: .
        dockerfile: GrpcServiceA/Dockerfile
    ports:
        - "50051:50051"  # Always map host:container ports
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:50051
      # RabbitMQ settings
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - RabbitMq__VirtualHost=/
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
    depends_on:
      - rabbitmq   # Ensure RabbitMQ is up before this service starts

  rest-service-b:
    container_name: rest-service-b
    build:
        context: .
        dockerfile: RestServiceB/Dockerfile
    ports:
        - "5000:5000"  # Always map host:container ports
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      # RabbitMQ settings
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - RabbitMq__VirtualHost=/
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
      - ./RestServiceB/Source/lastSum.txt:/app/lastSum.txt
    depends_on:
        - rabbitmq   # Ensure RabbitMQ is up before this service starts 

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
        - "5672:5672" # AMQP protocol
        - "15672:15672" # RabbitMQ Management UI
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest